alerta/angular-alerta-webui

app/js/app.js

add support for twitter login

---

app/config.js
app/index.html
app/js/app.js
app/js/controllers.js
app/partials/keys.html
app/partials/profile.html
app/partials/signup.html
app/vendor/satellizer.min.js

Client-side updates for guardian/alerta#85 server-side changes to support Basic Authentication.

Add basic auth for user logins

---

app/index.html
app/js/app.js
app/js/controllers.js
app/js/services.js
app/partials/blackouts.html

Add support for guardian/alerta#112

add blackout periods to config menu

---

app/config.js
app/js/app.js

Fixes guardian/alerta/issues/116

Add support for GitLab OAuth2 logins

---

app/js/controllers.js

Add 'by user' when console status change, if auth enabled

---

app/js/controllers.js
app/js/services.js
app/partials/blackouts.html

See guardian/alerta#168 for server-side changes.

Partition blackout periods by customer

---

app/partials/alert-details.html

Add history type column to alert details view

---

app/config.js
app/config.js.example
app/index.html
app/js/directives.js

**Example Config**
```
angular.module('config', [])
.constant('config', {
'endpoint'    : "http://"+window.location.hostname+":8080",
'provider'    : "basic", // google, github, gitlab or basic
'client_id'   : "INSERT-CLIENT-ID-HERE",
'gitlab_url'  : "https://gitlab.com",  // replace with your gitlab server
'colors'      : {}, // use default colors
'severity'    : {}, // use default severity codes
'audio'       : {}, // no audio
'tracking_id' : ""  // Google Analytics tracking ID eg. UA-NNNNNN-N
});
```

Make Google analytics tracking code a directive

---

app/partials/users.html

Show role in users list view

---

app/css/app.css
app/index.html
app/js/controllers.js
app/js/services.js
app/partials/alert-top10.html

Add top 10 flapping to Top 10 page and help popover

---

app/js/services.js

Use PUT not POST for tag, untag and status changes

---

app/partials/alert-details.html

Disable delete button if not admin

---

app/config.js
app/config.js.example
app/js/app.js
web.js

See related server-side changes guardian/alerta#334

Add support for GitHub Enterprise logins

---

app/config.js
app/js/app.js
app/js/controllers.js

Adding keycloak auth provider support

---

app/partials/alert-list.html

Always show customer column if customer views enabled ie. you don't need to be an admin to see the customer column.

Always show customer column if customer views enabled

---

app/partials/heartbeats.html

Show customers for heartbeats if customer views enabled

---

app/index.html

Allow users to add/modify alert blackouts

---

app/config.js
app/config.js.example
app/js/controllers.js

SAML 2.0 authentication

---

app/index.html
app/js/app.js
app/js/controllers.js
app/js/services.js
app/partials/alert-details.html
app/partials/keys.html
app/partials/perms.html
app/partials/profile.html
app/partials/users.html

Update user role...
List, add, remove user permissions...

Update user role and CRUD permissions

---

app/js/controllers.js
app/partials/keys.html
app/partials/profile.html

List API key scopes not key type

---

app/index.html
app/js/controllers.js

Reverts alerta/angular-alerta-webui#88

Revert "Fix permission validation."

---

app/index.html

Fix drop-down menu by permissions

---

app/js/controllers.js
app/partials/users.html

```
{
"iss": "http://localhost:5000/",
"sub": "180c412f-8691-49cf-8a19-7e7dcb65897d",
"aud": "http://localhost:5000/",
"exp": 1506976326,
"nbf": 1505766726,
"iat": 1505766726,
"jti": "d1157c76-ce4c-4256-b85f-90849315746f",
"name": "Administrator",
"preferred_username": "admin@alerta.io",
"email": "admin@alerta.io",
"provider": "basic",
"roles": [
"admin"
],
"scope": "admin read write"
}
```

Use preferred username in JWT

---

app/js/controllers.js

Username instead of email for basic auth login

---

app/js/controllers.js

Add support for blackout status

---

app/config.js
app/js/app.js

webui changes to support ping federate sso authentication (openid using pingefederate)

changes to support pingfederate sso

---

app/js/controllers.js
app/partials/alert-details.html

Alarm shelving for temporary removal from main alert list

---

app/js/controllers.js
app/partials/profile.html

Allow users to belong to multiple customers

---

app/js/controllers.js

Fixes #129 The drop-downs won't look right but the wanted filters should be applied correctly.

Set status filter from URL parameters

---

app/config.js
app/config.js.example
app/js/controllers.js

Fix default refresh interval

---

app/js/controllers.js
app/partials/blackouts.html

Add support for extra blackout audit info

---

app/partials/alert-details.html

Disable shelve button if no permissions

---

app/config.js
app/js/controllers.js
app/partials/login.html
app/partials/signup.html

Add setting to enable/disable user signup

---

app/partials/profile.html

Show text if customers is *

---

app/css/app.css
app/index.html
app/js/controllers.js

Make navbar site logo a config option

---

app/js/controllers.js

Add missing statuses to top10 dropdown

---

app/js/controllers.js
app/partials/users.html

Fixes #157 Requires https://github.com/alerta/alerta/pull/709

Add admin user create user form

---

app/partials/blackouts.html

Help for tag-based blackouts

---

app/index.html
app/js/controllers.js
app/partials/blackouts.html

Show all possible menus for non-authenticated users

---

app/js/bootstrap.js
app/js/config.js

Bring web UI into line with CLI alerta/python-alerta-client#159 and alerta/alerta/issues/715

Use any local config over downloaded remote config

---

app/index.html
app/js/controllers.js
app/partials/alert-list.html
app/partials/alert-watch.html

Add search box to navigation bar

---

app/index.html
app/js/controllers.js
app/partials/alert-list.html

hi, Nick. sorry for late. it works. not sure about:
1. where I should documented it
2. what about columns? I heard, you already did it. can you please comment?

add kiosk mode for main dashboard

---

app/js/controllers.js
app/partials/users.html

Default user role included by API now

---

app/partials/perms.html
app/partials/users.html

Add filter for users and roles pages

---

app/index.html

Fix menu for small screens

---

app/js/controllers.js

Bulk actions should not use status endpoint

---

app/js/bootstrap.js

Show error dialog if missing or invalid config.json file

---

app/js/auth.js

Add support for Microsoft Azure OAuth2 login

---

app/js/auth.js

See alerta/alerta#875 and alerta/alerta#876

Add support for OpenID Connect OAuth2 login

---

app/js/controllers.js

Fix environment tab counts
